version: '2'
services:
  redis:
    image: redis

  app:
    stdin_open: true
    tty: true
    build: .
    ports:
      - '8000:8000'
    environment:
      - CACHE="REDIS"
      - CACHE_REDIS_HOST=redis
      - CACHE_REDIS_PORT=6379
    links:
      - 'redis'