version: '2'
services:
  redis:
    image: redis

  app:
    stdin_open: true
    tty: true
    build: .
    ports:
      - '3000:3000'
    environment:
      - CACHE_REDIS_HOST=redis
      - CACHE_REDIS_PORT=6379
      - STUDIO_URL="https://ghibliapi.herokuapp.com"
      - MOVIE_URL="/films"
      - PEOPLE_URL="people"
    links:
      - 'redis'